build_from:
  amd64: "lscr.io/linuxserver/obsidian:amd64-v1.9.14-ls94@sha256:39c4e7f21dc4c3cb3c47b0dde547ee7a7b1909cee236fb31655d7ff01e9c4cc2"
  aarch64: "lscr.io/linuxserver/obsidian:arm64v8-v1.9.14-ls94@sha256:3e43e5f2d6552ed856695c555991a58ac490fbe53146a787ca1f615caab5ad3d"
labels:
  org.opencontainers.image.title: "Home Assistant Obsidian"
  org.opencontainers.image.description: "Runs Obsidian within your Home Assistant setup providing integration of live-features"
  org.opencontainers.image.source: "https://github.com/crazyrokr/ha-obsidian/tree/main/obsidian"
  org.opencontainers.image.licenses: "MIT license"
