---
name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  run-builder:
    uses: crazyrokr/gha-workflows/.github/workflows/ha-addon-cicd.yaml@master
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
